### ISSUE TITLE
poll failed [WinError 64] The specified network name is no longer available

### ISSUE THREAD

**Issue by E-Bommel** [Pinsplash/halflife2chaos#90]
**Describe the bug**
Twitch integration script is running into the error poll failed [WinError 64] The specified network name is no longer available when starting up

**To Reproduce**
1. In OBS scripts console
2. Either on startup or reloding script
3. after the startup step done

**Additional context**
install of the setup.bat finished without issue besides in step 10 where it thows this line
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 55484: character maps to <undefined>
we manuall added the .py into the scripts then

script stack is as follows:
[Unknown Script] connection stuff done
[Unknown Script] startup done
[Unknown Script] poll failed [WinError 64] The specified network name is no longer available
[Unknown Script] Bot is ready for work, joining channels

RCON host is set to default with password just set to 123 in this case, interesting case here is that if I set the password to anything that's 6 digits or longer I get this error instead: poll unexpected exception: 8 is not a valid Type

the text source is updated with Vote #-1 so that seems to be working fine

**Comment by acuifex** [comment]
This seems related: https://github.com/Pinsplash/halflife2chaos/issues/52

Can you check if there is something else listening on port 27015?

**Comment by E-Bommel** [comment]
> This seems related: #52
> 
> Can you check if there is something else listening on port 27015?

there was indeed something listening on that port, after closing it I now get the error:
poll failed [WinError 1225] The remote computer refused the network connection
is there a way to change the port to something else to make sure that there's no interference from anything else?

**Comment by Pinsplash** [comment]
there's maybe a chance that this is happening because of the recent changes to twitch/yt integration that haven't yet made it into a release but are still... you know? so the solution here may just be to make a release since it's about time to

**Comment by acuifex** [comment]
https://github.com/Pinsplash/halflife2chaos/compare/v0.2.11...b615b7b
I don't see any breaking changes to integration so i think most of the issues were already there.

**Comment by E-Bommel** [comment]
> > is there a way to change the port to something else to make sure that there's no interference from anything else?
> 
> I think you can change it with `-port <number>` game command argument. Make sure to change the port in obs to the new port `127.0.0.1:<number>`
> 
> > [WinError 1225] The remote computer refused the network connection
> 
> Either the game didn't start the rcon server, or windows firewall (or something else) is blocking the connection

changed the port to one higher (27016) with the -port in the startup params and it works, thanks for the quick help, might be worth adding the port stuff to the installation guide :D

seems "[WinError 1225] The remote computer refused the network connection" is just a very stupid way of saying "there isn't anything listening" which means, starting the game and then refreshing the script makes it worky
